### ISSUE TITLE
Epic task: replace `React.`

### ISSUE THREAD

**Issue by MengLinMaker** [MengLinMaker/tanstack-svelte-router#63]
## Why?
Another approach to tackling porting with cyclic dependencies

### ScriptOnce.tsx
- [ ] 6:}: { children: string; log?: boolean } & React.HTMLProps<HTMLScriptElement>) {

### scroll-restoration.tsx
- [ ] 8:  typeof window !== 'undefined' ? React.useLayoutEffect : React.useEffect

### matchContext.tsx
- [ ] 3:export const matchContext = React.createContext<string | undefined>(undefined)

#### useBlocker.tsx
- [ ] 41:  const [resolver, setResolver] = React.useState<BlockerResolver>({
- [ ] 47:  React.useEffect(() => {

### Match.tsx
- [ ] 22:export const Match = React.memo(function MatchImpl({
- [ ] 61:      ? React.Suspense
- [ ] 100:              return React.createElement(routeNotFoundComponent, error as any)
- [ ] 111:export const MatchInner = React.memo(function MatchInnerImpl({
- [ ] 133:  const out = React.useMemo(() => {
- [ ] 139:  //   const ref = React.useRef(value)
- [ ] 256:export const Outlet = React.memo(function OutletImpl() {
- [ ] 258:  const matchId = React.useContext(matchContext)
- [ ] 303:      <React.Suspense fallback={pendingElement}>{nextMatch}</React.Suspense>

### CatchBoundary.tsx
- [ ] 7:  children: React.ReactNode
- [ ] 19:          return React.createElement(errorComponent, {
- [ ] 31:class CatchBoundaryImpl extends React.Component<{
- [ ] 36:  }) => React.ReactNode
- [ ] 81:  const [show, setShow] = React.useState(process.env.NODE_ENV !== 'production')

Transitioner.tsx
- [ ] 10:  const mountLoadForRouter = React.useRef({ router, mounted: false })
- [ ] 16:  const [isTransitioning, startReactTransition_] = React.useTransition()
- [ ] 37:  React.useEffect(() => {

### Matches.tsx
- [ ] 169:  meta?: Array<React.JSX.IntrinsicElements['meta']>
- [ ] 170:  links?: Array<React.JSX.IntrinsicElements['link']>
- [ ] 171:  scripts?: Array<React.JSX.IntrinsicElements['script']>
- [ ] 214:      : React.Suspense
- [ ] 293:  return React.useCallback(
- [ ] 335:    | React.ReactNode
- [ ] 392:  const contextMatchId = React.useContext(matchContext)
- [ ] 412:  const contextMatchId = React.useContext(matchContext)

RouterProvider.tsx
- [ ] 65:  children: React.ReactNode

useRouter.tsx
- [ ] 9:  const value = React.useContext(getRouterContext())

useNavigate.tsx
- [ ] 25:  return React.useCallback(
- [ ] 59:  React.useEffect(() => {

utils.ts
- [ ] 6:  const fnRef = React.useRef(fn)
- [ ] 9:  const ref = React.useRef((...args: Array<any>) => fnRef.current(...args))
- [ ] 14:  typeof window !== 'undefined' ? React.useLayoutEffect : React.useEffect
- [ ] 21:  const ref = React.useRef<{ value: T; prev: T | null }>({
- [ ] 57: * const ref = React.useRef<HTMLDivElement>(null)
- [ ] 68:  ref: React.RefObject<T>,
- [ ] 73:  const isIntersectionObserverAvailable = React.useRef(
- [ ] 77:  const observerRef = React.useRef<IntersectionObserver | null>(null)
- [ ] 79:  React.useEffect(() => {
- [ ] 103: * React hook to take a `React.ForwardedRef` and returns a `ref` that can be used on a DOM element.
- [ ] 109: * const MyComponent = React.forwardRef((props, ref) => {
- [ ] 115:export function useForwardedRef<T>(ref?: React.ForwardedRef<T>) {
- [ ] 116:  const innerRef = React.useRef<T>(null)
- [ ] 118:  React.useEffect(() => {

not-found.tsx
- [ ] 36:  fallback?: (error: NotFoundError) => React.ReactElement
- [ ] 38:  children: React.ReactNode

route.ts
- [ ] 371:  onCatch?: (error: Error, errorInfo: React.ErrorInfo) => void
- [ ] 456:  }) => Array<React.JSX.IntrinsicElements['meta']>
- [ ] 457:  links?: () => Array<React.JSX.IntrinsicElements['link']>
- [ ] 458:  scripts?: () => Array<React.JSX.IntrinsicElements['script']>
- [ ] 1665:  | React.LazyExoticComponent<(props: TProps) => ReactNode>

routerContext.tsx
- [ ] 4:const routerContext = React.createContext<Router<any, any>>(null!)

lazyRouteComponent.tsx
- [ ] 20:}: React.PropsWithChildren<{ fallback?: React.ReactNode }>) {
- [ ] 29:  return React.useSyncExternalStore(
- [ ] 112:          {React.createElement(comp, props)}
- [ ] 116:    return React.createElement(comp, props)

awaited.tsx
- [ ] 56:    fallback?: React.ReactNode
- [ ] 57:    children: (result: T) => React.ReactNode
- [ ] 62:    return <React.Suspense fallback={props.fallback}>{inner}</React.Suspense>
- [ ] 69:    fallback?: React.ReactNode
- [ ] 70:    children: (result: T) => React.ReactNode
- [ ] 72:): React.JSX.Element {
- [ ] 74:  return props.children(data) as React.JSX.Element

router.ts
- [ ] 105:    __TSR_ROUTER_CONTEXT__?: React.Context<Router<any, any>>
- [ ] 291:  defaultOnCatch?: (error: Error, errorInfo: React.ErrorInfo) => void
- [ ] 396:  Wrap?: (props: { children: any }) => React.JSX.Element
- [ ] 406:  InnerWrap?: (props: { children: any }) => React.JSX.Element

link.tsx
- [ ] 586:  forwardedRef?: React.ForwardedRef<Element>,
- [ ] 587:): React.ComponentPropsWithRef<'a'> {
- [ ] 589:  const [isTransitioning, setIsTransitioning] = React.useState(false)
- [ ] 590:  const hasRenderFetched = React.useRef(false)
- [ ] 636:  const type: 'internal' | 'external' = React.useMemo(() => {
- [ ] 647:  const next = React.useMemo(
- [ ] 651:  const preload = React.useMemo(
- [ ] 704:  const doPreload = React.useCallback(() => {
- [ ] 711:  const preloadViewportIoCallback = React.useCallback(
- [ ] 740:      ref: innerRef as React.ComponentPropsWithRef<'a'>['ref'],
- [ ] 836:  const resolvedActiveProps: React.HTMLAttributes<HTMLAnchorElement> = isActive
- [ ] 841:  const resolvedInactiveProps: React.HTMLAttributes<HTMLAnchorElement> =
- [ ] 867:    ref: innerRef as React.ComponentPropsWithRef<'a'>['ref'],
- [ ] 886:type UseLinkReactProps<TComp> = TComp extends keyof React.JSX.IntrinsicElements
- [ ] 887:  ? React.JSX.IntrinsicElements[TComp]
- [ ] 888:  : React.PropsWithoutRef<
- [ ] 889:      TComp extends React.ComponentType<infer TProps> ? TProps : never
- [ ] 891:      React.RefAttributes<
- [ ] 893:          | React.FC<{ ref: infer TRef }>
- [ ] 894:          | React.Component<{ ref: infer TRef }>
- [ ] 950:    | React.ReactNode
- [ ] 954:      }) => React.ReactNode)
- [ ] 989:) => React.ReactElement
- [ ] 994:  return React.forwardRef(function CreatedLink(props, ref) {
- [ ] 999:export const Link: LinkComponent<'a'> = React.forwardRef<Element, any>(
- [ ] 1017:    return React.createElement(
